version: '3'
services:
  memory-bank:
    build: .
    volumes:
      - ./docs:/app/docs
    environment:
      - MEMORY_BANK_LANGUAGE=ja
    # Use tty and stdin_open for interactive mode
    tty: true
    stdin_open: true
