name: Test

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop] # master への push トリガーを削除

# コンカレンシー制御 - 同じブランチで同時に実行されないようにする
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] # Remove 18.x and 21.x due to dependency incompatibilities

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile

      # Build the entire project using TypeScript project references
      - name: Build project
        run: yarn build
      - name: Check Dependencies
        run: yarn check:deps # Add depcheck step
      - name: Run ESLint
        run: yarn lint
      - name: Run Integration Tests # Change to run integration tests
        run: yarn test:integration
