name: Test

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]

# コンカレンシー制御 - 同じブランチで同時に実行されないようにする
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] # Remove 18.x and 21.x due to dependency incompatibilities

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      
      # Build schemas package first, then mcp package, then the root package
      - name: Build packages in order
        run: |
          yarn workspace @memory-bank/schemas build
          yarn workspace @memory-bank/mcp build
          yarn build
          
          # Setup symlinks for schemas package to fix cross-package dependencies
          mkdir -p packages/mcp/node_modules/@memory-bank/schemas
          cp -r packages/schemas/dist/* packages/mcp/node_modules/@memory-bank/schemas/
          cp packages/schemas/package.json packages/mcp/node_modules/@memory-bank/schemas/
          # Fix package.json paths
          sed -i 's/"main": "dist\/index.js"/"main": "index.js"/g' packages/mcp/node_modules/@memory-bank/schemas/package.json
          sed -i 's/"module": "dist\/index.js"/"module": "index.js"/g' packages/mcp/node_modules/@memory-bank/schemas/package.json
          sed -i 's/"types": "dist\/index.d.ts"/"types": "index.d.ts"/g' packages/mcp/node_modules/@memory-bank/schemas/package.json
      
      - run: yarn test
