name: Test

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop]

# コンカレンシー制御 - 同じブランチで同時に実行されないようにする
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'yarn' # Disable yarn cache for debugging CI issues
      - run: yarn install --frozen-lockfile
      # - name: Force reinstall dependencies # Remove force install step
      #   run: yarn install --force

      # Check linked packages in node_modules for debugging
      - name: Check linked packages in node_modules
        run: ls -la node_modules/@memory-bank

      # Clean TypeScript build cache before building
      - name: Clean TypeScript build cache
        run: find . -name '*.tsbuildinfo' -delete

      # Build schemas package explicitly first (to ensure dist exists)
      - name: Build schemas package explicitly
        run: yarn workspace @memory-bank/schemas build

      # Build the project using the build script (which includes copying assets)
      - name: Build project
        run: yarn build

      - name: Check Dependencies
        run: yarn check:deps
      - name: Run ESLint
        run: yarn lint
      - name: Run Unit Tests
        run: yarn workspace @memory-bank/mcp test:unit
      - name: Run Integration Tests
        run: yarn workspace @memory-bank/mcp test:integration
      # - name: Run E2E Tests # ★コメントアウト★
      #  run: yarn workspace @memory-bank/mcp test:e2e # ★コメントアウト★

